---
title: "Trabalho Controle de Qualidade"
author: "Ariel Matheus Cordeiro Barbosa, Rafael Hilário Cruz Peixoto  e Tales Pereira Rodrigues"
date: "09/03/2021"
output: html_document
---


```{r setup, include=FALSE}
library(qcc)
tabela <- read.csv("Tabela.csv",header = T,sep = ";",dec = ",")
dados <- read.csv("Grupo 5.csv",header = T, dec = ",", sep = ";")
dados3 <- read.csv("Grupo 5  -  2.csv",header = T, dec = ",", sep = ";")
dados2 <- dados3[,3:4]
medias <- data.frame(mean(dados$Response[1:10]),mean(dados$Response[11:20]),mean(dados$Response[21:30]))
mediasR <- data.frame(mean(dados2$R[1:5]),mean(dados2$R[6:10]),mean(dados2$R[11:5]))
colnames(medias) <- c("Steve" ,  "Billie" , "Nathan")
colnames(mediasR) <- c("Steve" ,  "Billie" , "Nathan")
```


```{r}
dados
dados3
medias
mediasR
```

#Gráficos de Controle
```{r}
plot.xbar = qcc(dados2, type="xbar")
plot.R = qcc(dados2, type="R")
```


#Análise de Capacidade 
```{r}
lie <- 13
lse <- 17
process.capability(object = plot.xbar,
                   spec.limits=c(lie,lse))
```


#Avaliação do Sistema de Medição
```{r}

d2 <- tabela$d2[2-1]

r=abs(dados2$Mesure.1-dados2$Mesure.2)

sigrepe=mean(r)/d2

a <- (max(medias)-min(medias))/tabela$d2[3-1]
b <- (sigrepe^2)/6
sigrepro2 <- a^2-b

if(sigrepro2<=0){sigrepro2 <- 0}


sigmed2 <- sigrepe^2+sigrepro2

ReR <- 6*sqrt(sigmed2)

PReR <- ReR/(6*sd(dados$Response))*100

PT <- ReR/(lse-lie)*100

resp <- list("DP repe" = sigrepe , "DP repro" = sqrt(sigrepro2) , "Var med" = sigmed2 , "R&R" = ReR , "%R&R" = PReR , "PT" = PT)

resp

```
Observa-se que $\%R\&R=97.41726\%$. Portanto, com base neste resultado, o sistema de medição não se apresenta adequado. Para melhor avaliarmos a adequação do sistema, calcula-se a Porcentagem de Tolerância (PT).

Observa-se que, como $PT=174.6135\%$, o sistema de medição, de fato, se mostra inadequado.